### ISSUE TITLE
String with no attributes causes exception

### ISSUE THREAD

**Issue by MartinSchultz** [Bestfastfire/super_rich_text#1]
If I have a text with no attributes at all, I get an exception:

════════ Exception caught by widgets library ════════
The following FormatException was thrown building SuperRichText(dirty):
Nothing to repeat*.*?*

The relevant error-causing widget was: 
  SuperRichText file:///Users/.../lib/helper/RichTextWidget.dart:66:12
When the exception was thrown, this was the stack: 
#0      new _RegExp (dart:core-patch/regexp_patch.dart:219:51)
#1      new RegExp (dart:core-patch/regexp_patch.dart:29:15)
#2      SuperRichText.build.<anonymous closure> (package:super_rich_text/super_rich_text.dart:172:17)
#3      List.forEach (dart:core-patch/growable_array.dart:285:8)
#4      SuperRichText.build (package:super_rich_text/super_rich_text.dart:163:16)
...
══════════════

The use case is that the Widget first displays a loading text without attributes and then later some text with attributes like * or / is displayed.

**Comment by Bestfastfire** [comment]
> If I have a text with no attributes at all, I get an exception:
> 
> ════════ Exception caught by widgets library ════════
> The following FormatException was thrown building SuperRichText(dirty):
> Nothing to repeat*._?_
> 
> The relevant error-causing widget was:
> SuperRichText file:///Users/.../lib/helper/RichTextWidget.dart:66:12
> When the exception was thrown, this was the stack:
> #0 new _RegExp (dart:core-patch/regexp_patch.dart:219:51)
> #1 new RegExp (dart:core-patch/regexp_patch.dart:29:15)
> #2 SuperRichText.build. (package:super_rich_text/super_rich_text.dart:172:17)
> #3 List.forEach (dart:core-patch/growable_array.dart:285:8)
> #4 SuperRichText.build (package:super_rich_text/super_rich_text.dart:163:16)
> ...
> ══════════════
> 
> The use case is that the Widget first displays a loading text without attributes and then later some text with attributes like * or / is displayed.

Ty for report, its will fix soon

**Comment by kgass** [comment]
> If I have a text with no attributes at all, I get an exception:
> 
> ════════ Exception caught by widgets library ════════
> The following FormatException was thrown building SuperRichText(dirty):
> Nothing to repeat*._?_
> 
> The relevant error-causing widget was:
> SuperRichText file:///Users/.../lib/helper/RichTextWidget.dart:66:12
> When the exception was thrown, this was the stack:
> #0 new _RegExp (dart:core-patch/regexp_patch.dart:219:51)
> #1 new RegExp (dart:core-patch/regexp_patch.dart:29:15)
> #2 SuperRichText.build. (package:super_rich_text/super_rich_text.dart:172:17)
> #3 List.forEach (dart:core-patch/growable_array.dart:285:8)
> #4 SuperRichText.build (package:super_rich_text/super_rich_text.dart:163:16)
> ...
> ══════════════
> 
> The use case is that the Widget first displays a loading text without attributes and then later some text with attributes like * or / is displayed.

quick fix for me was adding `**` at the start of the text string.

**Comment by Bestfastfire** [comment]
It fixed now
