### ISSUE TITLE
Text styling gets lost on scrolling

### ISSUE THREAD

**Issue by kgass** [Bestfastfire/super_rich_text#2]
When scrolling up and down the Styling gets lost and the input Text is displayed:

![big](https://user-images.githubusercontent.com/37659158/78588296-a634b900-783e-11ea-8c23-0a373bf85fe6.gif)

Here you can see the used Code:
```
return Center(
              child: ListView.builder(
                itemCount: 10,
                scrollDirection: Axis.vertical,
                cacheExtent: 100.0,
                padding: EdgeInsets.symmetric(vertical: 10.0),
                itemBuilder: (BuildContext context, int index) {

                  String material = '*—*';

                  return GestureDetector(
                      child: Container(
                        decoration: BoxDecoration(
                            border: Border.all(),
                            borderRadius: BorderRadius.circular(12)),
                        margin: EdgeInsets.symmetric(
                            vertical: 10.0, horizontal: 10.0),
                        padding: EdgeInsets.symmetric(
                            vertical: 10.0, horizontal: 10.0),
                        child: Column(
                          children: <Widget>[
                            Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: <Widget>[
                                Flexible(
                                  child: Column(
                                    children: <Widget>[
                                      SuperRichText(
                                        text:
                                            'Item',
                                        style: Theme.of(context)
                                            .textTheme
                                            .headline5,
                                      ),
                                    ],
                                  ),
                                )
                              ],
                            ),
                            Divider(),
                            Row(
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: <Widget>[
                                Tooltip(
                                  message: 'Spieldauer',
                                  height: 24,
                                  child: Icon(Icons.timer),
                                ),
                                Padding(
                                  padding: const EdgeInsets.only(right: 7.0),
                                ),
                                Text('5 -20 Min.',
                                  style: Theme.of(context).textTheme.bodyText1,
                                ),
                                Spacer(
                                  flex: 1,
                                ),
                                Divider(),
                                Spacer(
                                  flex: 1,
                                ),
                                Tooltip(
                                  message: 'Gruppengröße',
                                  height: 24,
                                  child: Icon(Icons.group),
                                ),
                                Padding(
                                  padding: const EdgeInsets.only(right: 7.0),
                                ),
                                Text('1 - 3',
                                  style: Theme.of(context).textTheme.bodyText1,
                                ),
                              ],
                            ),
                            Divider(),
                            Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: <Widget>[
                                Tooltip(
                                  message: 'Material',
                                  height: 24,
                                  child: Icon(Icons.build),
                                ),
                                Padding(
                                  padding: const EdgeInsets.only(right: 7.0),
                                ),
                                new Flexible(
                                  child: Column(
                                    children: <Widget>[
                                      SuperRichText(
                                        text: '$material',
                                        style: Theme.of(context)
                                            .textTheme
                                            .bodyText1,
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                      onTap: () {
                      });
                },
              ),
            );
          ```

**Comment by Bestfastfire** [comment]
> When scrolling up and down the Styling gets lost and the input Text is displayed:
> 
> ![big](https://user-images.githubusercontent.com/37659158/78588296-a634b900-783e-11ea-8c23-0a373bf85fe6.gif)
> 
> Here you can see the used Code:
> 
> ```
> return Center(
>               child: ListView.builder(
>                 itemCount: 10,
>                 scrollDirection: Axis.vertical,
>                 cacheExtent: 100.0,
>                 padding: EdgeInsets.symmetric(vertical: 10.0),
>                 itemBuilder: (BuildContext context, int index) {
> 
>                   String material = '*—*';
> 
>                   return GestureDetector(
>                       child: Container(
>                         decoration: BoxDecoration(
>                             border: Border.all(),
>                             borderRadius: BorderRadius.circular(12)),
>                         margin: EdgeInsets.symmetric(
>                             vertical: 10.0, horizontal: 10.0),
>                         padding: EdgeInsets.symmetric(
>                             vertical: 10.0, horizontal: 10.0),
>                         child: Column(
>                           children: <Widget>[
>                             Row(
>                               crossAxisAlignment: CrossAxisAlignment.start,
>                               children: <Widget>[
>                                 Flexible(
>                                   child: Column(
>                                     children: <Widget>[
>                                       SuperRichText(
>                                         text:
>                                             'Item',
>                                         style: Theme.of(context)
>                                             .textTheme
>                                             .headline5,
>                                       ),
>                                     ],
>                                   ),
>                                 )
>                               ],
>                             ),
>                             Divider(),
>                             Row(
>                               crossAxisAlignment: CrossAxisAlignment.center,
>                               children: <Widget>[
>                                 Tooltip(
>                                   message: 'Spieldauer',
>                                   height: 24,
>                                   child: Icon(Icons.timer),
>                                 ),
>                                 Padding(
>                                   padding: const EdgeInsets.only(right: 7.0),
>                                 ),
>                                 Text('5 -20 Min.',
>                                   style: Theme.of(context).textTheme.bodyText1,
>                                 ),
>                                 Spacer(
>                                   flex: 1,
>                                 ),
>                                 Divider(),
>                                 Spacer(
>                                   flex: 1,
>                                 ),
>                                 Tooltip(
>                                   message: 'Gruppengröße',
>                                   height: 24,
>                                   child: Icon(Icons.group),
>                                 ),
>                                 Padding(
>                                   padding: const EdgeInsets.only(right: 7.0),
>                                 ),
>                                 Text('1 - 3',
>                                   style: Theme.of(context).textTheme.bodyText1,
>                                 ),
>                               ],
>                             ),
>                             Divider(),
>                             Row(
>                               crossAxisAlignment: CrossAxisAlignment.start,
>                               children: <Widget>[
>                                 Tooltip(
>                                   message: 'Material',
>                                   height: 24,
>                                   child: Icon(Icons.build),
>                                 ),
>                                 Padding(
>                                   padding: const EdgeInsets.only(right: 7.0),
>                                 ),
>                                 new Flexible(
>                                   child: Column(
>                                     children: <Widget>[
>                                       SuperRichText(
>                                         text: '$material',
>                                         style: Theme.of(context)
>                                             .textTheme
>                                             .bodyText1,
>                                       ),
>                                     ],
>                                   ),
>                                 ),
>                               ],
>                             ),
>                           ],
>                         ),
>                       ),
>                       onTap: () {
>                       });
>                 },
>               ),
>             );
>           ```
> ```

Will be fix soon

**Comment by Bestfastfire** [comment]
> When scrolling up and down the Styling gets lost and the input Text is displayed:
> 
> ![big](https://user-images.githubusercontent.com/37659158/78588296-a634b900-783e-11ea-8c23-0a373bf85fe6.gif)
> 
> Here you can see the used Code:
> 
> ```
> return Center(
>               child: ListView.builder(
>                 itemCount: 10,
>                 scrollDirection: Axis.vertical,
>                 cacheExtent: 100.0,
>                 padding: EdgeInsets.symmetric(vertical: 10.0),
>                 itemBuilder: (BuildContext context, int index) {
> 
>                   String material = '*—*';
> 
>                   return GestureDetector(
>                       child: Container(
>                         decoration: BoxDecoration(
>                             border: Border.all(),
>                             borderRadius: BorderRadius.circular(12)),
>                         margin: EdgeInsets.symmetric(
>                             vertical: 10.0, horizontal: 10.0),
>                         padding: EdgeInsets.symmetric(
>                             vertical: 10.0, horizontal: 10.0),
>                         child: Column(
>                           children: <Widget>[
>                             Row(
>                               crossAxisAlignment: CrossAxisAlignment.start,
>                               children: <Widget>[
>                                 Flexible(
>                                   child: Column(
>                                     children: <Widget>[
>                                       SuperRichText(
>                                         text:
>                                             'Item',
>                                         style: Theme.of(context)
>                                             .textTheme
>                                             .headline5,
>                                       ),
>                                     ],
>                                   ),
>                                 )
>                               ],
>                             ),
>                             Divider(),
>                             Row(
>                               crossAxisAlignment: CrossAxisAlignment.center,
>                               children: <Widget>[
>                                 Tooltip(
>                                   message: 'Spieldauer',
>                                   height: 24,
>                                   child: Icon(Icons.timer),
>                                 ),
>                                 Padding(
>                                   padding: const EdgeInsets.only(right: 7.0),
>                                 ),
>                                 Text('5 -20 Min.',
>                                   style: Theme.of(context).textTheme.bodyText1,
>                                 ),
>                                 Spacer(
>                                   flex: 1,
>                                 ),
>                                 Divider(),
>                                 Spacer(
>                                   flex: 1,
>                                 ),
>                                 Tooltip(
>                                   message: 'Gruppengröße',
>                                   height: 24,
>                                   child: Icon(Icons.group),
>                                 ),
>                                 Padding(
>                                   padding: const EdgeInsets.only(right: 7.0),
>                                 ),
>                                 Text('1 - 3',
>                                   style: Theme.of(context).textTheme.bodyText1,
>                                 ),
>                               ],
>                             ),
>                             Divider(),
>                             Row(
>                               crossAxisAlignment: CrossAxisAlignment.start,
>                               children: <Widget>[
>                                 Tooltip(
>                                   message: 'Material',
>                                   height: 24,
>                                   child: Icon(Icons.build),
>                                 ),
>                                 Padding(
>                                   padding: const EdgeInsets.only(right: 7.0),
>                                 ),
>                                 new Flexible(
>                                   child: Column(
>                                     children: <Widget>[
>                                       SuperRichText(
>                                         text: '$material',
>                                         style: Theme.of(context)
>                                             .textTheme
>                                             .bodyText1,
>                                       ),
>                                     ],
>                                   ),
>                                 ),
>                               ],
>                             ),
>                           ],
>                         ),
>                       ),
>                       onTap: () {
>                       });
>                 },
>               ),
>             );
>           ```
> ```

fixed
