### ISSUE TITLE
One function for marker

### ISSUE THREAD

**Issue by everancii** [Bestfastfire/super_rich_text#3]
Good day, first of all want to say that this extension is beautiful. I'd like it alot.
I faced a problem  in my project. I have Marker with function 
```
  MarkerText.withFunction(
        marker: '/19/',
        functions: [() => print("test")],
        style: styleMarker),
```
and my text String looks like this
`var textString = "The main part of /19/this/19/ is identical with /19/Rule/19/ of the ";`

So print is only work on first word in string. But it doesnt work on second word. Its works fine if  i write second function in list of functions
```
    MarkerText.withFunction(
        marker: '/19/',
        functions: [() => print("test"), () => print("test")],
        style: styleMarker),
```
but it is not very convenient way to solve the problem because in my text could be a lot of specific part with same marker tag, and for each of them i should past the same function. Thanks in advance

**Comment by Bestfastfire** [comment]
> Good day, first of all want to say that this extension is beautiful. I'd like it alot.
> I faced a problem in my project. I have Marker with function
> 
> ```
>   MarkerText.withFunction(
>         marker: '/19/',
>         functions: [() => print("test")],
>         style: styleMarker),
> ```
> 
> and my text String looks like this
> `var textString = "The main part of /19/this/19/ is identical with /19/Rule/19/ of the ";`
> 
> So print is only work on first word in string. But it doesnt work on second word. Its works fine if i write second function in list of functions
> 
> ```
>     MarkerText.withFunction(
>         marker: '/19/',
>         functions: [() => print("test"), () => print("test")],
>         style: styleMarker),
> ```
> 
> but it is not very convenient way to solve the problem because in my text could be a lot of specific part with same marker tag, and for each of them i should past the same function. Thanks in advance

Yes, when I created this feature I ended up putting it in the same marker you have to repeat the function as you did in example 2 because in a text there could be several words that perform different functions but in the same style, which looking at your point is really annoying to replicate , so while I don't update, you can store your function in a variable and just replicate it:

```
var myFun = () => print('teste');

MarkerText.withFunction(
        marker: '/19/',
        functions: [myFun, myFun],
        style: styleMarker),
```

Soon I will add another type of marker for when all words have the same style and the same function, different from what we currently have, so the user has the 2 possibilities.

**Comment by Bestfastfire** [comment]
> Good day, first of all want to say that this extension is beautiful. I'd like it alot.
> I faced a problem in my project. I have Marker with function
> 
> ```
>   MarkerText.withFunction(
>         marker: '/19/',
>         functions: [() => print("test")],
>         style: styleMarker),
> ```
> 
> and my text String looks like this
> `var textString = "The main part of /19/this/19/ is identical with /19/Rule/19/ of the ";`
> 
> So print is only work on first word in string. But it doesnt work on second word. Its works fine if i write second function in list of functions
> 
> ```
>     MarkerText.withFunction(
>         marker: '/19/',
>         functions: [() => print("test"), () => print("test")],
>         style: styleMarker),
> ```
> 
> but it is not very convenient way to solve the problem because in my text could be a lot of specific part with same marker tag, and for each of them i should past the same function. Thanks in advance

Lib updated, added:

MarkerText.withSameFunction(
        marker: '<sf>',
        function: () => print('my Fun'),
        style: styleMarker),

**Comment by Bestfastfire** [comment]
> Good day, first of all want to say that this extension is beautiful. I'd like it alot.
> I faced a problem in my project. I have Marker with function
> 
> ```
>   MarkerText.withFunction(
>         marker: '/19/',
>         functions: [() => print("test")],
>         style: styleMarker),
> ```
> 
> and my text String looks like this
> `var textString = "The main part of /19/this/19/ is identical with /19/Rule/19/ of the ";`
> 
> So print is only work on first word in string. But it doesnt work on second word. Its works fine if i write second function in list of functions
> 
> ```
>     MarkerText.withFunction(
>         marker: '/19/',
>         functions: [() => print("test"), () => print("test")],
>         style: styleMarker),
> ```
> 
> but it is not very convenient way to solve the problem because in my text could be a lot of specific part with same marker tag, and for each of them i should past the same function. Thanks in advance

Lib updated, added:

```
MarkerText.withSameFunction(
        marker: '<sf>',
        function: () => print('my Fun'),
        style: styleMarker),

```

**Comment by everancii** [comment]
This is great, thank you
